name: MDPreviewFinderExtension
options:
  deploymentTarget:
    macOS: "10.15"
settings:
  base:
    CODE_SIGNING_ALLOWED: NO
    SWIFT_VERSION: "5.0"
targets:
  MDPreviewFinderExtension:
    type: app-extension
    platform: macOS
    sources:
      - FinderSyncExtension.swift
    info:
      path: ExtensionInfo.plist
      properties:
        CFBundleDisplayName: MD Preview
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSUIElement: true
        NSExtension:
          NSExtensionAttributes: {}
          NSExtensionPointIdentifier: com.apple.FinderSync
          NSExtensionPrincipalClass: MDPreviewFinderSync
        NSPrincipalClass: NSApplication
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mdpreview.app.FinderExtension
        PRODUCT_NAME: MDPreviewFinderExtension
        MARKETING_VERSION: "1.2.0"
        CURRENT_PROJECT_VERSION: "1.2.0"
        CODE_SIGN_ENTITLEMENTS: Extension.entitlements
